<?php
session_start();

if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header("Location: admin-login.php");
    exit();
}

// Database connection
$conn = new mysqli("localhost", "root", "", "planetarium_db");
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

$success_message = '';
$error_message = '';
$body_data = null;

// Handle form submission for updates
if ($_SERVER["REQUEST_METHOD"] == "POST" && isset($_POST['update'])) {
    $body_id = $conn->real_escape_string($_POST['body_id']);
    $category = $conn->real_escape_string($_POST['category']);
    $name = $conn->real_escape_string($_POST['name']);
    $temperature = $conn->real_escape_string($_POST['temperature']);
    $age = $conn->real_escape_string($_POST['age']);
    $description = $conn->real_escape_string($_POST['description']);
    $distance = $conn->real_escape_string($_POST['distance']);
    $table = $category . "s";

    // Start with basic update SQL
    $update_sql = "UPDATE $table SET 
                   name = '$name',
                   temperature = '$temperature',
                   age = '$age',
                   description = '$description',
                   distance = '$distance'";

    // Handle image upload if a new image is provided
    if (isset($_FILES["image"]) && $_FILES["image"]["size"] > 0) {
        $target_dir = "../../uploads/";
        $file_extension = strtolower(pathinfo($_FILES["image"]["name"], PATHINFO_EXTENSION));
        $new_filename = $name . "_" . time() . "." . $file_extension;
        $target_file = $target_dir . $new_filename;
        $db_image_path = "uploads/" . $new_filename;

        if (move_uploaded_file($_FILES["image"]["tmp_name"], $target_file)) {
            // Get old image path to delete later
            $old_image_query = "SELECT image_path FROM $table WHERE id = $body_id";
            $old_image_result = $conn->query($old_image_query);
            if ($old_image_row = $old_image_result->fetch_assoc()) {
                $old_image_path = "../../" . $old_image_row['image_path'];
                if (file_exists($old_image_path)) {
                    unlink($old_image_path);
                }
            }

            // Add image path to update query
            $update_sql .= ", image_path = '$db_image_path'";
        } else {
            $error_message = "Error uploading new image.";
        }
    }

    // Complete and execute the update query
    $update_sql .= " WHERE id = $body_id";
    
    if ($conn->query($update_sql) === TRUE) {
        // Update the individual page file
        $safe_name = preg_replace('/[^a-zA-Z0-9\-_]/', '', str_replace(' ', '-', $name));
        $page_filename = $safe_name . "-" . $body_id . ".php";
        $category_dir = "../../categories/" . $category . "s/";
        $full_page_path = $category_dir . $page_filename;

        $page_content = "<?php
// Individual page for $name
// Auto-generated by Cosmic Horizons Planetarium System

// Set the specific body ID and category for this page
\$_GET['id'] = $body_id;
\$_GET['category'] = '$category';

// Include the template
include '../../body_page_template.php';
?>";

        if (file_put_contents($full_page_path, $page_content)) {
            $success_message = "Celestial body updated successfully!";
        } else {
            $success_message = "Celestial body updated successfully! (Warning: Could not update individual page file)";
        }
    } else {
        $error_message = "Error updating record: " . $conn->error;
    }
}

// Get the body data to edit
if (isset($_GET['id']) && isset($_GET['category'])) {
    $edit_id = $conn->real_escape_string($_GET['id']);
    $edit_category = $conn->real_escape_string($_GET['category']);
    $table = $edit_category . "s";
    
    $sql = "SELECT * FROM $table WHERE id = $edit_id";
    $result = $conn->query($sql);
    if ($result && $result->num_rows > 0) {
        $body_data = $result->fetch_assoc();
    } else {
        header("Location: edit-body.php");
        exit();
    }
} else {
    header("Location: edit-body.php");
    exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit <?php echo htmlspecialchars($body_data['name']); ?> - Cosmic Horizons</title>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400;500;700&family=Share+Tech+Mono&display=swap" rel="stylesheet">
    <style>
        :root {
            --deep-space-blue: #0B1746;
            --nebula-purple: #4A2C5D;
            --hologram-cyan: #00FFD4;
            --starlight-white: #E6E6FA;
            --glow-pink: #FF00FF;
            --cosmic-black: #000000;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body, html {
            min-height: 100vh;
            font-family: 'Share Tech Mono', monospace;
            background: linear-gradient(135deg, var(--deep-space-blue), var(--nebula-purple));
            color: var(--starlight-white);
            overflow-x: hidden;
            position: relative;
        }

        .overlay {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: repeating-linear-gradient(
                0deg,
                rgba(0, 0, 0, 0.15),
                rgba(0, 0, 0, 0.15) 1px,
                transparent 1px,
                transparent 2px
            );
            pointer-events: none;
            z-index: 1000;
        }

        .cosmic-background {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: 
                radial-gradient(circle at 30% 50%, rgba(0,255,212,0.1) 0%, transparent 50%),
                radial-gradient(circle at 70% 30%, rgba(255,0,255,0.1) 0%, transparent 50%),
                linear-gradient(135deg, var(--deep-space-blue), var(--nebula-purple));
            background-attachment: fixed;
            opacity: 0.8;
            z-index: -1;
        }

        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 2rem;
            position: relative;
            z-index: 100;
        }

        .form-container {
            background: rgba(11, 23, 70, 0.6);
            padding: 2rem;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 1px solid var(--hologram-cyan);
            box-shadow: 0 0 20px rgba(0, 255, 212, 0.2);
        }

        .form-group {
            margin-bottom: 1.5rem;
            width: 100%;
        }

        label {
            display: block;
            margin-bottom: 0.8rem;
            color: var(--hologram-cyan);
            letter-spacing: 1px;
            text-transform: uppercase;
            font-size: 0.9rem;
            font-family: 'Orbitron', sans-serif;
        }

        input, select, textarea {
            width: 100%;
            padding: 0.8rem;
            background: rgba(0, 255, 212, 0.05);
            border: 1px solid var(--hologram-cyan);
            color: var(--hologram-cyan);
            border-radius: 4px;
            font-family: 'Share Tech Mono', monospace;
            transition: all 0.3s ease;
            box-sizing: border-box;
        }

        textarea {
            min-height: 120px;
            resize: vertical;
        }

        input:focus, select:focus, textarea:focus {
            outline: none;
            border-color: var(--glow-pink);
            box-shadow: 0 0 10px rgba(255, 0, 255, 0.3);
        }

        input::placeholder, textarea::placeholder {
            color: rgba(0, 255, 212, 0.5);
        }

        input[type="file"] {
            padding: 0.5rem;
            background: transparent;
            border: none;
            color: var(--hologram-cyan);
        }

        input[type="file"]::-webkit-file-upload-button {
            background: transparent;
            border: 1px solid var(--hologram-cyan);
            color: var(--hologram-cyan);
            padding: 0.5rem 1rem;
            border-radius: 4px;
            font-family: 'Share Tech Mono', monospace;
            cursor: pointer;
            margin-right: 1rem;
            transition: all 0.3s ease;
        }

        input[type="file"]::-webkit-file-upload-button:hover {
            background: var(--hologram-cyan);
            color: var(--deep-space-blue);
        }

        .button-group {
            display: flex;
            gap: 1rem;
            margin-top: 2rem;
        }

        .control-btn {
            flex: 1;
            padding: 0.8rem;
            font-family: 'Orbitron', sans-serif;
            font-size: 1rem;
            cursor: pointer;
            transition: all 0.3s ease;
            text-transform: uppercase;
            letter-spacing: 1px;
            border-radius: 4px;
            background: transparent;
            border: 1px solid var(--hologram-cyan);
            color: var(--hologram-cyan);
        }

        .control-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 0 15px rgba(0, 255, 212, 0.3);
        }

        .submit-btn {
            background: var(--hologram-cyan);
            color: var(--deep-space-blue);
            border: 1px solid var(--hologram-cyan);
        }

        .submit-btn:hover {
            background: rgba(0, 255, 212, 0.8);
            box-shadow: 0 0 15px rgba(0, 255, 212, 0.5);
        }

        h2 {
            font-family: 'Orbitron', sans-serif;
            color: var(--hologram-cyan);
            text-align: center;
            margin-bottom: 2rem;
            font-size: 1.8em;
            text-transform: uppercase;
            letter-spacing: 2px;
            text-shadow: 0 0 10px rgba(0, 255, 212, 0.5);
        }

        .current-image {
            max-width: 200px;
            height: auto;
            border: 2px solid var(--hologram-cyan);
            border-radius: 4px;
            margin-bottom: 1rem;
            display: block;
        }

        .message {
            padding: 1rem;
            margin-bottom: 1rem;
            border-radius: 4px;
            text-align: center;
        }

        .success {
            background: rgba(0, 255, 0, 0.1);
            border: 1px solid #00ff00;
            color: #00ff00;
        }

        .error {
            background: rgba(255, 0, 0, 0.1);
            border: 1px solid #ff0000;
            color: #ff0000;
        }
    </style>
</head>
<body>
    <div class="overlay"></div>
    <div class="cosmic-background"></div>
    <div class="container">
        <div class="form-container">
            <h2>Edit <?php echo htmlspecialchars($body_data['name']); ?></h2>

            <?php if ($success_message): ?>
                <div class="message success"><?php echo $success_message; ?></div>
            <?php endif; ?>

            <?php if ($error_message): ?>
                <div class="message error"><?php echo $error_message; ?></div>
            <?php endif; ?>

            <form method="POST" enctype="multipart/form-data">
                <input type="hidden" name="body_id" value="<?php echo $body_data['id']; ?>">
                <input type="hidden" name="category" value="<?php echo $_GET['category']; ?>">

                <div class="form-group">
                    <label for="name">Celestial Body Name</label>
                    <input type="text" id="name" name="name" value="<?php echo htmlspecialchars($body_data['name']); ?>" required>
                </div>

                <div class="form-group">
                    <label for="temperature">Temperature</label>
                    <input type="text" id="temperature" name="temperature" value="<?php echo htmlspecialchars($body_data['temperature']); ?>" required>
                </div>

                <div class="form-group">
                    <label for="age">Age</label>
                    <input type="text" id="age" name="age" value="<?php echo htmlspecialchars($body_data['age']); ?>" required>
                </div>

                <div class="form-group">
                    <label for="distance">Distance</label>
                    <input type="text" id="distance" name="distance" value="<?php echo htmlspecialchars($body_data['distance']); ?>" required>
                </div>

                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea id="description" name="description" required><?php echo htmlspecialchars($body_data['description']); ?></textarea>
                </div>

                <div class="form-group">
                    <label>Current Image</label>
                    <img src="../../<?php echo htmlspecialchars($body_data['image_path']); ?>" alt="Current image" class="current-image">
                    <label for="image">Upload New Image (Optional)</label>
                    <input type="file" id="image" name="image" accept="image/*">
                </div>

                <div class="button-group">
                    <button type="button" class="control-btn" onclick="history.back()">Back to List</button>
                    <button type="submit" name="update" class="control-btn submit-btn">Update Body</button>
                </div>
            </form>
        </div>
    </div>
</body>
</html>