<?php
// Individual page for Earth
// Auto-generated by Cosmic Horizons Planetarium System

// Set the specific body ID and category for this page
$_GET['id'] = 9;
$_GET['category'] = 'planet';

// Include the template
include '../../body_page_template.php';
?>