<?php
// Individual page for Sun
// Auto-generated by Cosmic Horizons Planetarium System

// Set the specific body ID and category for this page
$_GET['id'] = 6;
$_GET['category'] = 'star';

// Include the template
include '../../body_page_template.php';
?>