<?php
// Individual page for Moon
// Auto-generated by Cosmic Horizons Planetarium System

// Set the specific body ID and category for this page
$_GET['id'] = 5;
$_GET['category'] = 'moon';

// Include the template
include '../../body_page_template.php';
?>